# Generated by Django 4.1.3 on 2023-01-19 13:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5b4073e2-c2c9-4437-801c-b66446e0cf68'), editable=False, primary_key=True, serialize=False),
        ),
    ]
