# Generated by Django 4.1.3 on 2023-01-20 14:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f36b8210-27d7-4ea0-b534-a592222d8712'), editable=False, primary_key=True, serialize=False),
        ),
    ]
