# Generated by Django 4.1.3 on 2023-01-13 20:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('71845605-0e48-435b-a03d-7cde1fc11f4c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
