# Generated by Django 4.1.3 on 2023-01-13 21:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('65a9da18-142e-4e6f-80ce-1ffa3efc992c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
