# Generated by Django 4.1.3 on 2023-01-20 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ecdfcc8a-5893-405e-8138-4d7d139bc700'), editable=False, primary_key=True, serialize=False),
        ),
    ]
