# Generated by Django 4.1.3 on 2023-01-19 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c1166875-d7e9-4cc9-bfb2-005a088023d9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
