# Generated by Django 4.1.3 on 2023-01-20 14:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6c7b1908-2322-4803-a8c1-f1ef3dce9c84'), editable=False, primary_key=True, serialize=False),
        ),
    ]
