# Generated by Django 4.1.3 on 2023-01-23 14:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('16da20ca-dfa9-4445-81a0-6ddaf9084e61'), editable=False, primary_key=True, serialize=False),
        ),
    ]
