# Generated by Django 4.1.3 on 2023-01-13 21:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c1fc6969-be2c-4b39-8345-7029c3534812'), editable=False, primary_key=True, serialize=False),
        ),
    ]
