# Generated by Django 4.1.3 on 2023-01-13 21:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('946e8f27-5d83-474d-adf9-8901cc4f1e7f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
