# Generated by Django 4.1.3 on 2023-01-13 22:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ec6a372e-f20f-45b5-aa39-19bbbafaadf1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
