# Generated by Django 4.1.3 on 2023-01-14 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7f180a39-a75f-4da8-b059-df5b74b80f93'), editable=False, primary_key=True, serialize=False),
        ),
    ]
