# Generated by Django 4.1.3 on 2023-01-14 11:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f7bd210b-97ed-433e-9e32-160aa121f446'), editable=False, primary_key=True, serialize=False),
        ),
    ]
