# Generated by Django 4.1.3 on 2023-01-14 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b3ab8bd8-6357-46ce-840a-d6a936f2fd80'), editable=False, primary_key=True, serialize=False),
        ),
    ]
