# Generated by Django 4.1.3 on 2023-01-14 11:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('255975dc-b98d-4045-a61b-64ed3272f94d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
