# Generated by Django 4.1.3 on 2023-01-14 11:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6ad07ea2-c02f-4718-98ed-1e6f95e81d9a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
