# Generated by Django 4.1.3 on 2022-11-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('rating', models.IntegerField()),
                ('image', models.CharField(blank=True, max_length=255)),
                ('video', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
