# Generated by Django 4.1.3 on 2023-01-23 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('26f1846b-c44b-4337-8b7d-58089cc8f366'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4460c181-7974-457d-8a24-9481d190d5d7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favoritepins',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b00a4c30-4c64-4311-b0dc-6d6e46d0418c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='id',
            field=models.UUIDField(default=uuid.UUID('708d9cc7-7de9-4316-a7e7-4f64b07ab650'), editable=False, primary_key=True, serialize=False),
        ),
    ]
