# Generated by Django 4.1.3 on 2023-01-23 14:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0002_alter_category_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mappoint',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('813ef35d-5a5b-4647-bccc-0232e11c1a79'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('86d20a0f-68b5-45f4-994e-a85b6bb732eb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favoritepins',
            name='id',
            field=models.UUIDField(default=uuid.UUID('be5b5056-a797-4cb3-a929-d7ff11870f11'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e31fb121-f9fd-4536-8c15-e935c463b10b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
