# Generated by Django 4.1.3 on 2022-12-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0002_remove_comment_image_remove_comment_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_id',
        ),
    ]
