# Generated by Django 4.1.3 on 2023-01-19 13:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0006_merge_20230109_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('51e6286e-ccf4-4291-b4cd-62a3b7684fcb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5834021f-b469-455f-8722-1ca11f24ddd2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favoritepins',
            name='id',
            field=models.UUIDField(default=uuid.UUID('270579b7-d3c3-4b94-9eb0-edd1b09b990a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6bc4e68d-fd26-4b5d-8e06-2dc2d61c62b9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
