# Generated by Django 4.1.3 on 2023-01-20 14:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0007_alter_category_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d9faf700-1824-4033-83db-721e0c0810d8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('550579b6-9528-4909-b143-4eded73b01a7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favoritepins',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c87d4887-c6ef-4387-9b16-65b7ad60d8e9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='id',
            field=models.UUIDField(default=uuid.UUID('43b4e877-ffc1-4c26-981f-331fcf3362bf'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('mappoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='get_outside.mappoint')),
            ],
        ),
    ]
