# Generated by Django 4.1.3 on 2023-01-19 13:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0007_alter_category_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b6c9c221-c60f-4dde-a17b-a440da3d26ba'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('98ab9eb7-cfd0-42c0-bdca-5ee2d8e0f934'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favoritepins',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6042f20b-5959-4e8b-b340-d669c003a9cf'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='id',
            field=models.UUIDField(default=uuid.UUID('21f8aa97-f820-4c32-8a72-1bf439aa3916'), editable=False, primary_key=True, serialize=False),
        ),
    ]
