# Generated by Django 4.1.3 on 2023-01-14 11:47

import datetime
from django.db import migrations, models
import get_outside.models.presenceModel
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0007_alter_category_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('34558a5f-a18b-4cf6-84b0-b43e2a25cbc0'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.TimeField(default=datetime.datetime(2023, 1, 14, 12, 47, 44, 124971))),
                ('end_at', models.TimeField(default=get_outside.models.presenceModel.default_start_time)),
                ('pin', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3f292ee3-f81d-4398-87d3-a2cc824936d3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favoritepins',
            name='id',
            field=models.UUIDField(default=uuid.UUID('65a55e7e-89fb-4727-a64f-c74d20628b81'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='id',
            field=models.UUIDField(default=uuid.UUID('627c4eb3-44af-4207-8cc5-4ad370d13cf3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
