# Generated by Django 4.1.3 on 2023-01-19 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0008_alter_category_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9268485a-9d37-431f-96fb-91fdec94c3d7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f0b5afae-a7cc-4f1c-b198-1a84c5a4a17a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favoritepins',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ac11de0c-8342-410b-84b9-6c3b90d8fd27'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0919cfcc-7dbc-43a4-ada4-2be0e77bab89'), editable=False, primary_key=True, serialize=False),
        ),
    ]
