# Generated by Django 4.1.3 on 2023-01-20 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0008_alter_category_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1592029c-62a4-403a-91ae-730309f2952d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('680fef83-2cd6-4c73-aba8-d79b95e2e7ab'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favoritepins',
            name='id',
            field=models.UUIDField(default=uuid.UUID('213a6783-7221-43ea-b5c6-beaa4cbcae62'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b81fab64-80fb-4418-bd24-5f8e8e60d2de'), editable=False, primary_key=True, serialize=False),
        ),
    ]
