# Generated by Django 4.1.3 on 2023-01-14 11:48

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0008_presence_alter_category_options_remove_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoint',
            name='visitor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4a759fb4-404d-47b2-b33d-a4e63a6f08e2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favoritepins',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7d6b066d-0ab0-4456-b424-7117c7f84fb0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e8151671-b172-49b6-a45d-bdb1415d5411'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='presence',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2023, 1, 14, 12, 48, 16, 231275)),
        ),
        migrations.AlterField(
            model_name='presence',
            name='id',
            field=models.UUIDField(default=uuid.UUID('93745841-e44a-4698-bbb3-1283cb0282a7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
