# Generated by Django 4.1.3 on 2023-01-14 11:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0009_mappoint_visitor_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc4095b2-65e5-49a6-8a13-f8da136f72f0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favoritepins',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d2b80ce2-f0cd-4836-b1de-6b47dc16eea2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9f37d640-fca2-40c9-9a66-22759d1961d4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='presence',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2023, 1, 14, 12, 52, 40, 594016)),
        ),
        migrations.AlterField(
            model_name='presence',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cdf34be2-4b90-4f8b-b73d-7451d4b23348'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='presence',
            name='pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_outside.mappoint'),
        ),
    ]
