# Generated by Django 4.1.3 on 2023-01-20 14:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0009_alter_category_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a2cc5e05-55ee-466e-9778-f63ea3c02573'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('61c150d0-d3fe-4be4-afb9-bac8252d0785'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favoritepins',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c27a6558-b7a8-46d2-9ffb-3744f4710308'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6f7444a3-c928-4258-9eae-9a1f430b65a6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
