# Generated by Django 4.1.3 on 2023-01-14 12:20

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0010_alter_comment_id_alter_favoritepins_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('eadb12b5-ef8b-4e0a-983e-5904a4489a05'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favoritepins',
            name='id',
            field=models.UUIDField(default=uuid.UUID('40001808-b133-42e6-a9e2-92abfd3fdc41'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6892a2e0-b406-411b-b990-cae0d0339304'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='presence',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2023, 1, 14, 13, 20, 9, 733364)),
        ),
        migrations.AlterField(
            model_name='presence',
            name='id',
            field=models.UUIDField(default=uuid.UUID('505c61c3-5876-4e88-a7a6-dd6a3d02a76d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
