# Generated by Django 4.1.3 on 2023-01-16 15:16

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0011_alter_comment_id_alter_favoritepins_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d17f4900-aa3a-453e-8f64-5415c036dff8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favoritepins',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5e045ef1-4c96-4242-ab5c-d527201d97b6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f0c9f1bc-996b-47ac-b544-8247a85058a9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='presence',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2023, 1, 16, 16, 16, 13, 287469)),
        ),
        migrations.AlterField(
            model_name='presence',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0242420e-0c12-44cd-a0d8-c953185854e9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
