# Generated by Django 4.1.3 on 2023-01-16 15:18

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0012_alter_comment_id_alter_favoritepins_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('81e36016-8e2b-4ab8-b264-75d868d44d82'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favoritepins',
            name='id',
            field=models.UUIDField(default=uuid.UUID('73ec221b-cff7-4efd-a45a-34522c6b8af3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='presence',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2023, 1, 16, 16, 18, 1, 538745)),
        ),
        migrations.AlterField(
            model_name='presence',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2b83803c-24e8-4017-af3a-301e057f0585'), editable=False, primary_key=True, serialize=False),
        ),
    ]
